# Generated by Django 6.0 on 2025-12-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='directors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='writers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='content',
            name='poster_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
